[package]
name = "trafficserver-ffi"
version = "7.1.2"
authors = ["James Peach <jpeach@apache.org>"]
build = "build.rs"

[build-dependencies]
bindgen = "0.33.1"
serde = "*"
serde_json = "*"
serde_derive = "*"
